server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minichat
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 898265866051-e7bbonmegmbj0458ldetmg0ejo518pu7.apps.googleusercontent.com
            client-secret: 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